version: '3.7'

services:
  eurekaserver:
    image: aangdocker/eureka:0.0.1-SNAPSHOT
    ports:
      - "8070:8070"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://configservice:8071

networks:
  default:
    external: true
    name: config-server-dockersied_config-server-network