spring:
  application:
    name: eureka-server

    loadbalancer:
      ribbon:
        enabled: false

  config:
    import: "optional:configserver:"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8070